apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    tier: registry
    app: finances
spec:
  selector:
    matchLabels:
      tier: registry
  template:
    metadata:
      labels:
        tier: registry
    spec:
      containers:
        - name: registry
          image: docker893/registry:v1
          ports:
            - containerPort: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  labels:
    tier: config
    app: finances
spec:
  selector:
    matchLabels:
      tier: config
  template:
    metadata:
      labels:
        tier: config
    spec:
      containers:
        - name: config
          image: docker893/config:v1
          ports:
            - containerPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    tier: gateway
spec:
  selector:
    matchLabels:
      tier: gateway

  template:
    metadata:
      labels:
        tier: gateway
    spec:
      containers:
        - name: gateway
          image: docker893/gateway:v1
          ports:
            - containerPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    tier: account-service
spec:
  selector:
    matchLabels:
      tier: account-service
  template:
    metadata:
      labels:
        tier: account-service
    spec:
      containers:
        - name: account-service
          image: docker893/account-service:v1
          ports:
            - containerPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    tier: auth-service
spec:
  selector:
    matchLabels:
      tier: auth-service
  template:
    metadata:
      labels:
        tier: auth-service
    spec:
      containers:
        - name: auth-service
          image: docker893/auth-service:v1
          ports:
            - containerPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    tier: postgres
spec:
  selector:
    matchLabels:
      tier: postgres
  template:
    metadata:
      labels:
        tier: postgres
    spec:
      containers:
        - name: postgres
          image: docker893/postgres
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    tier: registry
spec:
  selector:
    tier: registry
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    tier: gateway
spec:
  selector:
    tier: gateway
  ports:
    - port: 80
      targetPort: 8084
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    tier: config
spec:
  selector:
    tier: config
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    tier: auth-service
spec:
  selector:
    tier: auth-service
  ports:
    - port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    tier: account-service
spec:
  selector:
    tier: account-service
  ports:
    - port: 8083
      targetPort: 8083





